### ISSUE TITLE
Warning spam every time a menu is opened.

### ISSUE THREAD

**Issue by Strahilchu** [rockyhawk64/CommandPanels#274]
### Terms

- [X] Have you checked the [wiki](https://rockyhawk99.gitbook.io/rockyhawk-wiki/commandpanels/wiki) page to see if there is a solution for your bug?
- [X] Have you looked at the [Current bugs project](https://github.com/rockyhawk64/CommandPanels/projects/6) to see if your bug is listed there?
- [X] Have you asked for help in the [Discord Server](https://discord.com/invite/eUWBWh7)? (Or got redirected to a Github issue here)
- [X] Did you search the [issue tracker](https://github.com/rockyhawk64/CommandPanels/issues?q=is%3Aissue) for a similar problem?

### What server version are you running?

1.19

### What CommandPanels version are you using?

latest

### What server software are you running?

Purpur

### What happened?

Used to not show Warning, seems to have randomly started.

### Steps to reproduce the issue

Unsure.

### Expected behavior

No warnings

### Error (optional)

```shell
[13:16:49 WARN]: Found inconsistent skull meta, this should normally not happen and is not a Bukkit / Spigot issue, but one from a plugin you are using.
Bukkit will attempt to fix it this time for you, but may not be able to do this every time.
If you see this message after typing a command from a plugin, please report this to the plugin developer, they should use the api instead of relying on reflection (and doing it the wrong way).
```

**Comment by TinyTank800** [comment]
https://github.com/rockyhawk64/CommandPanels/releases/tag/3.19.1.6

Try using this release. I believe Rocky has stated its only a test and is not currently in a release yet but should fix the error.

**Comment by Strahilchu** [comment]
I am on that version and error persists, unless this one is different? 3.19.1.6

**Comment by rockyhawk64** [comment]
It is the same version number yeah but the GitHub download contains a patch, it hasn't been released to Spigot quite yet so I would appreciate feedback as to whether it worked if you had time :)

**Comment by Strahilchu** [comment]
Ah yes this resolved the issue!
